### ISSUE TITLE
Add docs for creating a new umbrella repo

### ISSUE THREAD

**Issue by benlk** [INN/docs#106]
https://gist.github.com/benlk/badd80c6a6ed0d98b243 is draft, needs cleaning

**Comment by aschweigert** [comment]
this seems fine? https://github.com/INN/docs/blob/master/projects/largo/umbrella-setup.md

**Comment by benlk** [comment]
Reopening this issue to discuss:

- should we copy into this repo the instructions at https://gist.github.com/benlk/e4f555eb817940b817354f598408e57c for creating a new site from the ground up
- should we copy into this repo the instructions at https://github.com/INN/umbrella-boilerplate/blob/master/docs/README.md for instructions specific to the umbrella-boilerplate repository.
