### ISSUE TITLE
Newsletter contributor docs

### ISSUE THREAD

**Issue by benlk** [INN/docs#115]
- [ ] What we need from them\
- [ ] When we need it by
- [ ] What they get from it
- [ ] Why they should contribute

**Comment by aschweigert** [comment]
some of this already exists here https://github.com/INN/docs/tree/master/communications/newsletter

**Comment by benlk** [comment]
Yep, but it would be nice to have a link specific to contributors that we could give to potential contributors.

**Comment by aschweigert** [comment]
meh, i think this is sufficient: https://github.com/INN/docs/blob/master/communications/newsletter/sample-contributor-email.md
