### ISSUE TITLE
data project guidelines/style/resources

### ISSUE THREAD

**Issue by aschweigert** [INN/docs#15]
we can probably crib from https://github.com/propublica/guides and some of the IRE resources but we should at least collect these in one place to use as a reference

**Comment by aschweigert** [comment]
@danilito19 this might be something you could also start contributing to. This would eventually live in a "data" subfolder of https://github.com/INN/docs/tree/master/style-guides

**Comment by danilito19** [comment]
I will read pro publica's guide more closely and others if I find to get some ideas.

**Comment by danilito19** [comment]
Guidelines for working in a data project
* Where to get data (online sources, open-source data, government data, using APIs)
* How to work with different data formats
* Cleaning data
* Data analysis software
* Exploratory data analysis
* Data visualization
* Statistical - predictive modeling 

(Of course the topics to include will depend on the scope of our projects, but these are examples)

**Comment by aschweigert** [comment]
That makes sense to me as the sorts of things we would cover, but I want to make sure we're not duplicating things that already exist so we should try to just link to other resources wherever possible and only write our own if absolutely necessary (or if it's for something that no one else has covered well).
