### ISSUE TITLE
Site generator recommandation

### ISSUE THREAD

**Issue by pascalandy** [INN/docs#161]
Hey folks,

I'm not part of the INN community but I really love to way you build your docs over here. It's probably an example of what great docs is for any orgs. Because many people get **scary** when they see a README.md file on Github, I have this question:

1) Do you have any recommandation about how to use a git repo (like this one) to generate a site (Basically a markdown to html tool.)

2) Specifically, what would be the workflow? 
I'm looking to generate a /static-export folder that I could simply copy in my nginx server.

Thanks in advance :-)

**Comment by rclations** [comment]
Hey @pascalandy, thanks for the kind words!

Are you familiar with GitHub Pages? That might work well for your needs, since you can manage the content directly on GitHub, but still have a regular front-end for the site.
 
Here's some more information on that - https://pages.github.com

**Comment by pascalandy** [comment]
Absolutely!  But I want to deploy this over my own domain :)

**Comment by benlk** [comment]
GitHub Pages supports using your own domain name! https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by pascalandy** [comment]
Haha, good answer :)

But I still want to own the server. I'm a developer at heart :)

**Comment by aschweigert** [comment]
Hi @pascalandy might be best to drop by our office hours and/or open a support ticket for this. Can you email support@inn.org and/or signup for a slot here: https://docs.google.com/spreadsheets/d/1p-twn2D8oow7vXBfkcdYcZnVA4z8Q42OMs77KlHwf-g/edit? Thanks!
