### ISSUE TITLE
design style guide

### ISSUE THREAD

**Issue by aschweigert** [INN/docs#22]
the real thing

**Comment by aschweigert** [comment]
What's the expected ETA on this? There's overlap here between Largo/INN here so this should probably be created using Largo so it starts from those styles and then we'll build custom templates for the components/write additional styles where necessary and also use this as an opportunity to refactor a lot of the existing CSS. So...wondering if this should be moved to the Largo repo instead of here and then we'd just fork it for INN and make the modifications that are specific just to us (and make it easy for members using Largo to do the same).

**Comment by kaeti** [comment]
I want us to have something functional in the next couple of months — hopefully the barebones soon, and then we can build over time. @rnagle and I worked on getting the basic framework up (then things got bananatown). It would be great to be able to carve out at least an hour every week or something. I also think it's something David could really add to during his apprenticeship.

We were envisioning it as a pattern library a la http://ux.mailchimp.com/patterns and http://patterns.alistapart.com/. 

Ben shared this open source project, which could be an interesting way of generating something from the existing Largo styles, which we could then edit: http://styleguide.sc5.io/

(Here's a round up of other style guide generators from the master of style guides herself: http://alistapart.com/blog/post/style-guide-generator-roundup )

We could frame it as the Largo style guide, with a page for INN-specific styles and a page for brand guidelines. Or we could frame it as a INN style guide, and have a section for anything that is specific to general Largo styles. OR have two separate guides using the same general framework (like, styles.largoproject.org and styles.inn.org). The latter probably makes the most sense.


There's a https://github.com/INN/styles repo, so I think tickets and work can continue to live there (unless you think it's better to have it in the Largo repo).
