### ISSUE TITLE
the tribapps blog has finally disappeared :(

### ISSUE THREAD

**Issue by aschweigert** [INN/docs#225]
There's a broken link in https://github.com/INN/docs/blob/master/how-to-work-with-us/readme.md (http://blog.apps.chicagotribune.com/2014/03/05/everything-you-ever-wanted-to-know-about-the-news-apps-process).

The wayback machine does have a copy (https://web.archive.org/web/20160909203500/http://blog.apps.chicagotribune.com/2014/03/05/everything-you-ever-wanted-to-know-about-the-news-apps-process/) so maybe it's worth pulling from there (since this is a *great* post) or seeing if anyone still there can fix the link.

**Comment by benlk** [comment]
@aschweigert d'ya wanna open a PR for this? Otherwise I'll go ahead and do it tonight.
