### ISSUE TITLE
feature request/new project checklist

### ISSUE THREAD

**Issue by aschweigert** [INN/docs#32]
A process/checklist for evaluating feature requests for our major projects (largo, etc.), how we prioritize features, what we need from a requestor, etc.

This may also work as an intake checklist for completely new projects, although that might be a separate checklist...

**Comment by aschweigert** [comment]
This possibly overlaps with #48 although the intake process might be a bit different...what do you think?

**Comment by kaeti** [comment]
I think the support request process might overlap with feature requests a bit, but is very different from a new project checklist. So maybe we just need to clarify the scope of this ticket

**Comment by meredithinn** [comment]
Reviewing the intake project question, it looks like they could be modified to fit here.  
A resource to think about prioritizing requests 
http://programmers.stackexchange.com/questions/13958/how-do-you-manage-feature-requests-and-software-changes

Issues related to a recent upgrade or migration (most important).
Security fixes.
Broken functionality of the existing system.
Broken functionality in RC and beta features.
Paid feature requests.
R&D feature requests from a large part of the user base.
R&D feature requests from only one or two users.

**Comment by aschweigert** [comment]
Meredith's draft: https://docs.google.com/document/d/1ni_I8EwIqYTiP-4v__Cj4WLOulJMsP7Wq6TusCO5NMk/edit
