### ISSUE TITLE
design templates

### ISSUE THREAD

**Issue by aschweigert** [INN/docs#37]
The style guides for INN/Largo will likely include some of this but we should think about how we communicated design direction to members/clients in conjunction with #36 

- high level design direction
- style tiles
- typography
- etc

**Comment by aschweigert** [comment]
bumping this a bit because it would be good to start pulling this together in one form or another, having some standards/templates that can be easily referenced and reused, etc. kind of related to https://github.com/INN/ideas/issues/16

**Comment by kaeti** [comment]
Cool! Moving it up the priorities list.

There are a few different stages here. 

1. The UX and IA pieces — which could include user personas, card sorting/stacking exercises, site maps and content outlines, user interviews and surveys, etc. This is about listening, getting a sense of audience, and understanding the structure/goals of an organization.

2. Design discovery — maybe creating a checklist/questionnaire template for helping understand client's needs and wishes. These would be the questions and documents that help bridge the discussion from #1 to #3. We should also come away from discovery with a features list.

3. Design assets — Wireframes, typography, style tiles, mockups, and prototypes if they make sense for the project. 

Am I missing anything else that could be templatized here?

**Comment by aschweigert** [comment]
That seems about right to me. The UX/IA pieces we definitely need to do some work on documenting the sorts of things we might want to incorporate into a process, what they're for, how we'd do them "our way" etc. I think we have a decent handle on what those are in our heads but it would be good to get it all down somewhere.

Design discovery/assets both sound good to me. I'm especially interested in having a standard "look" for our deliverables and some templates for those to make our lives a bit easier. Might include things like proposals and the manifesto/project summary doc in there as well.
