### ISSUE TITLE
Add policy for working hours and schedule changes

### ISSUE THREAD

**Issue by tothebeat** [INN/docs#41]
It would be helpful to have some general policy on range of working hours, e.g. 9-5 EST or respective to your particular time zone, and under what situations this might be different:
- being on-call for support, emergency maintenance
- working on a major project rollout
- doctors appointments, errands, gym, lunch, etc. during the day

Setting some expectations of overlapping hours, when those will occur regularly and in what circumstances we may not be able to reach a teammate, is helpful when working on synchronous tasks.

This document would make the most sense linked from the section [How We Work](https://github.com/INN/docs/tree/master/how-we-work).

**Comment by aschweigert** [comment]
maybe we should figure out how to link to the employee manual here too (as long as we remember to update it when there's a new version)

**Comment by aschweigert** [comment]
this is covered by the employee manual, closing
