### ISSUE TITLE
Create baseline workstation setup guide in Onboarding

### ISSUE THREAD

**Issue by tothebeat** [INN/docs#42]
In the Onboarding section, it would be helpful to have a guide for the baseline workstation setup necessary to contribute to development and otherwise. A listing of software and necessary/recommended baseline config for each one.

I'm thinking of [Tyler Fisher's blog post on NPR Apps](http://blog.apps.npr.org/2013/06/06/how-to-setup-a-developers-environment.html) and [Brian Boyer's workstation setup notes](https://gist.github.com/brianboyer/1696819). These are developer-oriented, but I could see a core set of utilities and then breaking out into different roles in the INN team and what software/config is recommended/suggested for each.

**Comment by aschweigert** [comment]
let's go ahead and add the stuff from the blog post to the onboarding folder here as well
