### ISSUE TITLE
Add HelloSign section to Accounts and Tools

### ISSUE THREAD

**Issue by tothebeat** [INN/docs#43]
A personal [HelloSign](https://www.hellosign.com/home/index) account associated with your INN email is required for submitting expense reports. This is immediately necessary for buying 1Password as indicated in the [Accounts doc](https://github.com/inn/docs/blob/master/staffing/onboarding/accounts.md). This should be added as a section to the same Accounts doc, and perhaps to the [Tools doc](https://github.com/INN/docs/blob/master/how-we-work/tools.md) as well.

**Comment by meredithinn** [comment]
Added HelloSign to the Accounts doc
