### ISSUE TITLE
opportunities for feedback

### ISSUE THREAD

**Issue by aschweigert** [INN/docs#57]
- [x] 60 day reviews
- [x] annual reviews
- [x] optional group reviews?
- [x] other opportunities to get help/feedback on performance?

**Comment by aschweigert** [comment]
talking with @rnagle a bit about this today, would be curious to get other input on ways we could approach performance evaluation/feedback outside of "formal" reviews. cc: @kaeti @tothebeat

**Comment by kaeti** [comment]
Project retrospectives (I especially like the blameless post-mortem model: https://codeascraft.com/2012/05/22/blameless-postmortems/ )

**Comment by aschweigert** [comment]
@kaeti just added retrospectives to the meetings doc on friday (https://github.com/INN/docs/blob/master/how-we-work/meetings.md) would love some feedback on that though/anything else we should add there

**Comment by aschweigert** [comment]
Ryan's notes: https://gist.github.com/rnagle/0885617adbb883a9f154

**Comment by aschweigert** [comment]
first crack at this in https://github.com/INN/docs/commit/38a070b264be02cbeb175e9a0ed29b9fb396ce42 throwing to @kaeti for an edit

**Comment by kaeti** [comment]
https://github.com/INN/docs/pull/85
