### ISSUE TITLE
job descriptions from member organizations

### ISSUE THREAD

**Issue by aschweigert** [INN/docs#60]
It would be great to add tech/design/product related job descriptions from members to our job descriptions folder (https://github.com/INN/docs/tree/master/staffing/job-descriptions). This is really helpful for when members are hiring and looking for some guidance on what to include in their postings.

If you're willing to share yours, please either email us at nerds@inn.org or follow these instructions (https://github.com/INN/docs/blob/master/how-to-work-with-us/via-github.md) to fork this repo, add your job descriptions and then submit a pull request.

**Comment by aschweigert** [comment]
todo: assuming we have takers on this, we'll need to come up with a standard naming convention for files in that folder and organization scheme. Probably by job type rather than organization is going to make most sense.

**Comment by kaeti** [comment]
Do you think we should have a separate folder for member orgs vs. INN job descriptions?

**Comment by aschweigert** [comment]
yeah, i think eventually that's going to make more sense, and then organize the subfolders by job type...probably?

**Comment by meredithinn** [comment]
Is this something that might belong in the newsletter as a call to participate?

**Comment by aschweigert** [comment]
@meredithinn Not just yet, I want to think a bit more about other things we'd like member orgs to contribute and add those as issues here, write a blog post, etc. before we push too hard on that.

**Comment by aboutaaron** [comment]
I'll try and see if I can find the job description CIR gave me when I applied. Are y'all specifically lookign for news apps / design postings or should I also try to wrangle data reporter applications as well?

**Comment by aschweigert** [comment]
@aboutaaron I think data stuff would be useful too. Definitely thinking mostly about tech/design stuff because that's what people mostly ask us for help with but I don't think it would hurt to include some data stuff in the mix too in case people would find that useful.

**Comment by danilito19** [comment]
I'll pitch in to this task as well - it will help me research some of the member organizations and get to know what they work on.
