### ISSUE TITLE
Build a guide to submitting pull requests with examples

### ISSUE THREAD

**Issue by tothebeat** [INN/docs#64]
With a baseline of @rnagle's [introductory guide to working with us via Github](https://github.com/INN/docs/blob/master/how-to-work-with-us/via-github.md) and submitting a pull request, I think it would be helpful to show a few examples of real pull requests in the past that have had favorable qualities, along with pull requests with undesirable qualities that made the pull request unsuitable. If not a classification of a pull request as a whole being good or bad, it would be helpful to see a breakdown of a particular pull request into its favorable and unfavorable qualities.

As a beginner to submitting pull requests at all, not to mention to a project like Largo with well over 2000 commits, I find it a bit intimidating to submit a change. I don't have the luxury of being able to be scared off because I work here, but doing it the wrong way the first time and having a pull request rejected could scare off contributors without prior experience in submitting changes.

Even without going into qualifying a pull request or components of it as good or bad, it would be helpful to see a guided tour of a previous pull request so potential contributors would have some idea of what to expect from the process after they press the "submit pull request" button.

Does anything like this exist on other projects?

**Comment by aschweigert** [comment]
This is pretty similar to what I'd hope to accomplish with #62, but yeah, I think including an "anatomy of a good pull request" or examples of previous "correct" ones would be a nice thing to add.

**Comment by danilito19** [comment]
Can we discuss here what would make a "bad" pull request? What are some unfavorable qualities?

**Comment by aschweigert** [comment]
closing #62 as a duplicate and just adding a note here that this guide should at least link to this doc from TX Tribune: https://gist.github.com/risatrix/ceabdf7e8d00f9dbdd38 (ht @risatrix) which I think is pretty similar to what we need here.

**Comment by danilito19** [comment]
I'm going to make this applicable both for our team members and for those outside the INN team who may submit a PR. However, I can't quite decide if the doc should go [under work-with us](https://github.com/INN/docs/tree/master/how-to-work-with-us) or along with [onboarding and the other git guide](https://github.com/INN/docs/tree/master/staffing/onboarding) (or elsewhere?)

**Comment by aschweigert** [comment]
let's go with the "work with us" section (for now) and then link to it from the git guide and contributing.md in that same folder, we can always rearrange if that feels weird
