### ISSUE TITLE
project description for data/visuals content in largo working group

### ISSUE THREAD

**Issue by aschweigert** [INN/docs#73]

**Comment by aschweigert** [comment]
list of tools: https://mail.google.com/mail/u/0/#inbox/14d0084be85fc6f1

discovery survey draft: https://docs.google.com/document/d/1BeaSmBwXpgMjV_loN_JKQHxU93xKJ2e-_OgyMfBK-uk/edit

**Comment by benlk** [comment]
That list of tools appears to be a link to an email in your inbox?

**Comment by aschweigert** [comment]
whoops, updated

**Comment by meredithinn** [comment]
Thinking about additional tools to gain understanding of our members needs, I wonder if there might be an opportunity for a listening sessions (thinking Practical Empathy) to develop a case study or two around data/visuals content in Largo.
