### ISSUE TITLE
thoroughly document deployment process

### ISSUE THREAD

**Issue by aschweigert** [INN/docs#99]
for largo anyway, this should go in the projects/largo folder

**Comment by benlk** [comment]
The umbrella deploy, correct?

**Comment by aschweigert** [comment]
correct

**Comment by benlk** [comment]
I'm going to build off of this: https://gist.github.com/benlk/a433f60e7bc84f404eb9

**Comment by benlk** [comment]
WIP: https://github.com/INN/docs/compare/99-deployment-docs?name=99-deployment-docs&short_path=ef9d3c7#diff-ef9d3c7163e0ad17f9042b0243030194

**Comment by benlk** [comment]
Closing because of https://github.com/INN/deploy-tools/blob/master/docs/deploy.md
